### ISSUE TITLE
No possibility to leave comments

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-comments#10]
I installed grav 1.0.0 RC6 and then the comments plugin. I took a look at the 'Usage' section on this github page and did what was described:

1) Add the line to `templates/item.html.twig`
[item.html.twig.zip](https://github.com/getgrav/grav-plugin-comments/files/51360/item.html.twig.zip)

2) Copy `comments.yaml` from `user/plugins/comments/` to `user/config/plugins/`

Since i have a blog page with a child post and the `comments.yaml` already mentioned `- '/blog'` under the 'enable_on_routes:' section, i did't change anything there - only removed every entry under `disable_on_routes:` because i want to show comments on every blog post.
[comments.yaml.zip](https://github.com/getgrav/grav-plugin-comments/files/51357/comments.yaml.zip)

But i still can't add comments to my example blog post. Here is the page structure so far:
![pages](https://cloud.githubusercontent.com/assets/226475/11574361/8d556d64-9a0b-11e5-9090-b5fbc4ad21af.png)

Can someone please point me in the right direction and show me what i did wrong?

**Comment by flaviocopes** [comment]
Blog posts are of `item` page type, not `blog`. `blog` is the blog posts list page type.
So, your "First post" page uses the blog.html.twig template. not item.html.twig

**Comment by Endogen** [comment]
Damn! Thanks for your help. Works now :+1:
