### ISSUE TITLE
Name field autofocus scrolling page

### ISSUE THREAD

**Issue by superlou** [getgrav/grav-plugin-comments#11]
On the name input field, the `autofocus` attribute is set.  I think this is why when my pages with the comments template load, they scroll to the bottom and focus the name input.  Is this something that can be disabled, or is this intended behavior?

**Comment by flaviocopes** [comment]
I just disabled like 3 hours prior to your comment! https://github.com/getgrav/grav-plugin-comments/commit/897451312c431da42d8c816c087ed637d0ade291 need a release, but for now just apply that fix to your `comments.yaml` file

**Comment by flaviocopes** [comment]
Released update

**Comment by superlou** [comment]
For some reason, grav doesn't want to update to 1.1.1, but I manually made the change and it fixes the scrolling.  Thanks!
