### ISSUE TITLE
onFormProcessed not being called

### ISSUE THREAD

**Issue by superlou** [getgrav/grav-plugin-comments#13]
I've installed the comments plugin, version 1.1.2, and followed the instructions to display the form on all blog pages.  However, when I submit the form, it doesn't save any comments.  As a sanity check, I added this to comments.php:

```php
    public function onFormProcessed(Event $event)
    {
        $form = $event['form'];
        $action = $event['action'];
        $params = $event['params'];
        $grav['log']->info("here");   // Debug statement
        if (!$this->active) {
            return;
        }
```

The message does not show up in `tail -f logs/grav.log`.  I have configured my permissions using the following script:

```bash
#!/bin/sh
chown www-data:www-data .
chown -R www-data:www-data *
find . -type f -not -name "fix-permissions.sh" | xargs chmod 664
find ./bin -type f | xargs chmod 775
find . -type d | xargs chmod 775
find . -type d | xargs chmod +s
umask 0002
```

Are there any tricks to figure out why `onFormProcessed` doesn't seem to be called?  Is the debug statement a valid check?

**Comment by flaviocopes** [comment]
Are you getting an error about captcha above the comment form, once you enter the comment?
You must configure the recaptcha parameters, or delete the captcha processing. 
I'll disable captcha by default in the next update, with instructions on how to activate it, as it needs the site/secret keys to work.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-comments/commit/f25fbd7e20fc690501ec49af56cd76893ca1609e

**Comment by superlou** [comment]
No error on captcha before or after submitting the form.  I gave it my Recaptcha keys and the check itself seems to work fine.

**Comment by flaviocopes** [comment]
If you just add the 'addComment' process action to the form, is it called?

**Comment by superlou** [comment]
Sorry, how would I do that?  In `user/config/plugins/comments.yaml` I see a `form: process: addComment:` item, but it's empty.

**Comment by flaviocopes** [comment]
This should work, for example:

```
enabled: true
form:
    name: comments
    fields:
.......
    process:
        - addComment:
```

(mind the correct tabs indentation)

**Comment by superlou** [comment]
I'm not following.  In `comments.yaml`, I have the `addComment` item, but I think that came by default.  As shown in the first code snippet in my first post, a log message in `onFormProcessed` doesn't show up by tailing the log.

**Comment by flaviocopes** [comment]
I'm not sure why it should not! PM me your user/ folder via Gitter so I can test

**Comment by superlou** [comment]
I recreated the issue on Linux Mint 17, Apache/2.4.7, PHP 5.5.9.  I used the grav core + admin package for version 1.0.4.  I installed the current comments package with recaptcha disabled.  I had the same symptoms with no comments being added.  It seems an unlikely thing, but is anyone successful on a LAMP server?

**Comment by khanduras** [comment]
I'm getting something similar - it doesn't look like it's processing the 'addcomment' 
I'm using nginx/1.4.6  PHP 5.5.9-1ubuntu4.5

**Comment by flaviocopes** [comment]
Just spinned up a clean site on Linux and I recreated the problem. Not sure why it didn't happen on my test environment before.
Can you test my fix? https://github.com/getgrav/grav-plugin-comments/commit/a6476ab5278d130b18ffad04e124db2a41059b3b

**Comment by superlou** [comment]
I tested it on my localhost development site and on my blog, both running LAMP on Mint/Ubuntu, and the fix seems to work.
