### ISSUE TITLE
It is not possible to write comments without providing an email form

### ISSUE THREAD

**Issue by acki-m** [getgrav/grav-plugin-comments#14]
I removed the email form from my comments.yaml config.
Because I was getting
```
Address in mailbox given [] does not comply with RFC 2822, 3.6.2
```
Maybe somehow related to this issue: https://github.com/getgrav/grav-plugin-form/issues/27

Anyway, when I remove the email form, I get following error:
```
Undefined index: email 
```

**Comment by flaviocopes** [comment]
If you don't want the email field, you also need to remove the `process.email` field in the form. Otherwise the Form plugin tries to send the email anyway, but there's no field where to get it.

**Comment by acki-m** [comment]
These are basically two issues.
1)
When I have an enabled email is mandatory, I get this exception. I don't know what to do about this...
2)
Enabled the usage of the comments plugin, without proving any email field.

At the moment the only workaround to get this plugin running is the set following config in the email field.
```
validate:
            rule: email
            required: false
```

PS: I have removed the `process.email ` field.

**Comment by flaviocopes** [comment]
Ok sorry I checked, the email is mandatory for comments, at this point. As it is usually when commenting on sites.

The other issue you have might be that you have not configured the Email Plugin. Does the Email Plugin configuration contain the 'from' and 'to' email addresses?

**Comment by acki-m** [comment]
Yeah, please honor the mandatory flag in the comments.yaml file.

I have configured the email plugin.
But I have `to: ''` empty, because how should I now who should I sens the email?
Only `from:` is set with my website email address.

**Comment by flaviocopes** [comment]
`to` is the default for site notifications, when people submit forms, etc. The email action in the comment form sends an email to you informing about the comment. As explained in the Admin-side Email Plugin configuration, it's the default `to`. If you don't specify one in the `email` action, you need to fill it.

I'll make sure to raise an exception when this happens, to avoid that confusing error message.

**Comment by acki-m** [comment]
and why does my email contact form works?

**Comment by flaviocopes** [comment]
I don't know. Is that built using the Form plugin too? It uses the same `to` parameter.

**Comment by acki-m** [comment]
sure
