### ISSUE TITLE
Can't translate Comment form label and placeholders

### ISSUE THREAD

**Issue by bovisp** [getgrav/grav-plugin-comments#19]
Hi!

How does one translate the frontmatter defined in `/users/plugins/comments/comments.yaml`? The translations as defined in `/users/plugins/comments/languages.yaml` show up just fine:

![alt](http://159.203.17.23/screencapturecomments.jpg)

and I guess I could also translate the submit button text in my languages theme file. The form labels and placeholders as defined in `/users/plugins/comments/comments.yaml`, as far as I can see, cannot be translated.

Is there a way to do this?

**Comment by flaviocopes** [comment]
Looking into using translation strings instead of hardcoding a label / placeholder. Same for button text and form processing.

**Comment by flaviocopes** [comment]
https://github.com/getgrav/grav-plugin-comments/commit/9d38761d44b514d987404c3fb8950f728717f38b should do it. You can try this version. 

Needs the latest `develop` branch of the Form plugin btw, to include my latest commits here: https://github.com/getgrav/grav-plugin-form/commits/develop ..so you might want to wait for the next release of both these plugins.
