### ISSUE TITLE
Error after install plugin

### ISSUE THREAD

**Issue by Zoxon** [getgrav/grav-plugin-comments#2]
```
UnexpectedValueException thrown with message "RecursiveDirectoryIterator::__construct(D:/OpenServer/domains/graw/user/data/comments,D:/OpenServer/domains/graw/user/data/comments): "

Stacktrace:
#10 UnexpectedValueException in D:\OpenServer\domains\graw\user\plugins\comments\comments.php:207
#9 RecursiveDirectoryIterator:__construct in D:\OpenServer\domains\graw\user\plugins\comments\comments.php:207
#8 Grav\Plugin\CommentsPlugin:getFilesOrderedByModifiedDate in D:\OpenServer\domains\graw\user\plugins\comments\comments.php:250
#7 Grav\Plugin\CommentsPlugin:getLastComments in D:\OpenServer\domains\graw\user\plugins\comments\comments.php:126
#6 Grav\Plugin\CommentsPlugin:onPluginsInitialized in <#unknown>:0
#5 call_user_func in D:\OpenServer\domains\graw\vendor\symfony\event-dispatcher\EventDispatcher.php:164
#4 Symfony\Component\EventDispatcher\EventDispatcher:doDispatch in D:\OpenServer\domains\graw\vendor\symfony\event-dispatcher\EventDispatcher.php:53
#3 Symfony\Component\EventDispatcher\EventDispatcher:dispatch in D:\OpenServer\domains\graw\vendor\rockettheme\toolbox\Event\src\EventDispatcher.php:23
#2 RocketTheme\Toolbox\Event\EventDispatcher:dispatch in D:\OpenServer\domains\graw\system\src\Grav\Common\Grav.php:377
#1 Grav\Common\Grav:fireEvent in D:\OpenServer\domains\graw\system\src\Grav\Common\Grav.php:208
#0 Grav\Common\Grav:process in D:\OpenServer\domains\graw\index.php:37
```

Comments  v1.0.0

**Comment by aptly-io** [comment]
I see a similar issue.

Right after installing the plug-in.
Click on "comments" in the admin panel's  left menu side panel I get:

RecursiveDirectoryIterator::__construct(/home/franchan/public_html/grav-skeleton-deliver-site/user/data/comments): failed to open dir: No such file or directory 

stacktrace:
10. UnexpectedValueException …/­user/­plugins/­comments/­comments.php207
9. RecursiveDirectoryIterator __construct …/­user/­plugins/­comments/­comments.php207
8. Grav\Plugin\CommentsPlugin getFilesOrderedByModifiedDate …/­user/­plugins/­comments/­comments.php250
7. Grav\Plugin\CommentsPlugin getLastComments …/­user/­plugins/­comments/­comments.php126
6. Grav\Plugin\CommentsPlugin onPluginsInitialized <#unknown>0
5. call_user_func …/­vendor/­symfony/­event-dispatcher/­EventDispatcher.php160
4. Symfony\Component\EventDispatcher\EventDispatcher doDispatch …/­vendor/­symfony/­event-dispatcher/­EventDispatcher.php48
3. Symfony\Component\EventDispatcher\EventDispatcher dispatch …/­vendor/­rockettheme/­toolbox/­Event/­src/­EventDispatcher.php23
2. RocketTheme\Toolbox\Event\EventDispatcher dispatch …/­system/­src/­Grav/­Common/­Grav.php406
1. Grav\Common\Grav fireEvent …/­system/­src/­Grav/­Common/­Grav.php225
0. Grav\Common\Grav process …/­index.php37

**Comment by flaviocopes** [comment]
Thanks for reporting, fixed and will soon appear as a new update
