### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by rhukster** [getgrav/grav-plugin-comments#22]
Here's a list of features that would help to make Comments plugin even better!
- [x] ~~Cache comments for better performance (see stars)~~ https://github.com/getgrav/grav-plugin-comments/commit/60c8d091e62534e3f63818ca3000bd0416267df6
- [x] ~~Clear form on submission (shows previous comment currently)~~ https://github.com/getgrav/grav-plugin-comments/commit/0cf90a74d7c9d8270aa81ca592865d73f57d42b9
- [x] ~~Support nonce + captcha type validation~~ (captcha is already supported in the form building, see https://github.com/getgrav/grav-plugin-comments#enabling-recaptcha) - nonce is built-in as it uses the form plugin
- [x] ~~Handle logged in users by not requiring username/email~~ https://github.com/getgrav/grav-plugin-comments/commit/ee608539d469a814f0b13844d4bc9fcefea9401b
- [ ] Ability to edit/delete/moderate comments in admin
- [ ] Open/Close form submission box .. closed on submission?
- [ ] Support avatars/gravatars
- [ ] Detect 'identical-repeat-messages' from same user
- [ ] Support threaded comments
- [ ] Support quoting/markdown
- [ ] Nicer default formatting of comment output
- [ ] regex support in the allowed routes
- [ ] Ability to subscribe to all comments by id

**Comment by khanduras** [comment]
Hey there, if I may request the ability to submit comments using Javascript/AJAX rather than submit form, at all possible?

**Comment by Eggeriley** [comment]
Do you think it could be possible to delete commetns from the backend?

**Comment by flaviocopes** [comment]
@Eggeriley it's in the above list, just didn't make it yet.

**Comment by Raboo** [comment]
Feature request:
Add support for the new invisible reCAPTCHA
https://developers.google.com/recaptcha/docs/invisible

**Comment by flaviocopes** [comment]
@Raboo interesting, it's more a new Form plugin field, or an edit to the existing Captcha field, open an issue here instead: https://github.com/getgrav/grav-plugin-form/issues

**Comment by Raboo** [comment]
I guess someone beat me to it.
https://github.com/getgrav/grav-plugin-form/issues/132

**Comment by metbril** [comment]
@rhukster PR's have queued for over a year. Do you plan to merge this in the future? Or is this plugin no longer maintained?
