### ISSUE TITLE
Undefined property: Grav\Common\Grav::$user on Grav v1.1.1

### ISSUE THREAD

**Issue by aureolacodes** [getgrav/grav-plugin-comments#28]
Thanks for your work so far.

I just tried to install the plugin on Grav v1.1.1, PHP 5.5.26

No matter where I add the include line of the twig-template I always get the following error.
`0 - An exception has been thrown during the rendering of a template ("Undefined property: Grav\Common\Grav::$user") in "partials/comments.html.twig" at line 14.`

Seems like the problem was introduced in commit ee608539d469a814f0b13844d4bc9fcefea9401b. If I remove the check in this commit, the problem is gone (also the feature you introduced in this commit no longer works).

**Comment by flaviocopes** [comment]
Have you got the Login plugin installed? Or not?

**Comment by aureolacodes** [comment]
No, the login-plugin was missing. With the plugin installed the original code works. Thanks for the quick response.

I used `bin/gpm install comments` to install the plugin. I think login should be added as a dependency.

**Comment by flaviocopes** [comment]
Right, pushed an update that fixes the problem - not as a dependency, but checking if the Login plugin is available before using its functionality.

**Comment by aureolacodes** [comment]
This will still break, if the login plugin is not installed.

I tried to create a pull request, but I think I didn't do it properly. Here is my fix for the problem...
https://github.com/aureolacodes/grav-plugin-comments/pull/1

**Comment by flaviocopes** [comment]
Does not break as long as you don't have a `user/config/plugins/login.yaml` with `enabled: true`, or did you test and still got the issue? I tested again just for safety, and didnt' get any issue

**Comment by aureolacodes** [comment]
Sorry, I should have been more clear. The original error is gone, but if you try to post a comment the following error occurs: Identifier "user" is not defined.

**Comment by flaviocopes** [comment]
Right. Can you make a PR from your branch to the main one?
