### ISSUE TITLE
Comments not being displayed

### ISSUE THREAD

**Issue by leylaJudy** [getgrav/grav-plugin-comments#29]
Hello!! i installed the plugin and it appears on my page. i mention that i still didn't fill the email plugin infos, is this the reason why when i click the " submit" the comments doesn"t go  to data==>comments?

**Comment by flaviocopes** [comment]
By default the email plugin sends an email to the store owner. If the email plugin is not configured, it will fail and the form processing is skipped. 

Fill the email plugin settings, or copy the comments.yaml file to user/config/plugins/comments.yaml and remove `process.email` https://github.com/getgrav/grav-plugin-comments/blob/develop/comments.yaml#L68-L70
