### ISSUE TITLE
Comments appear on the wrong page.

### ISSUE THREAD

**Issue by mabushey** [getgrav/grav-plugin-comments#33]
I created a page template of `item-comments` for blog entries I want comments on. 

I changed 4 pages from `item` to `item-comment`, Adding a comment on "page2" seems to work correctly, however that comment appears on the other pages instead of the correct comments. If I clear cache then all pages get the comments from "page1".

The data under `user/data/comments/blog` is correct so I believe this is purely a caching issue.

**Comment by mabushey** [comment]
Another thing I don't really understand is when the template is `item` (Admin plugin Pages -> Advanced), I get a `Blog Item` tag. When I change the page template to `item-comment` the `Blog Item` tab goes away.

**Comment by flaviocopes** [comment]
The form is defined by the template. The template probably comes with an item.yaml file in its blueprints/ folder. Example: https://github.com/getgrav/grav-theme-antimatter/blob/develop/blueprints/item.yaml. That's what defines the *Blog Item* tab.

If you now change your page file name, the blueprint is now different, so you need to go in your theme, copy the item.yaml to item-comment.yaml.

Caching issue, did not replicate yet, are you using a caching plugin or is this just the Grav Pages cache?

**Comment by mabushey** [comment]
Awesome, I copied over the `item-comment` blueprint file and that tab is back. Good info to know. :) So much of Grav just seems to make sense, I've been quite impressed and happy with it.

I'm just using Grav's caching. I had switched it to Redis for a bit but it broke so I'm back to normal caching. From system.yaml:
```
 61 cache:
 62   enabled: true
 63   check:
 64     method: file
 65   driver: auto
 66   prefix: wwwmir
 67   lifetime: 604800
 68   gzip: false
```

**Comment by mabushey** [comment]
I did the composer updates:

```
bin/composer.phar self-update
bin/composer.phar clearcache
bin/composer.phar update

bin/grav clean
bin/grav composer
bin/grav clear-cache
```

I still have the problem where the comment for the first page shows up on all the pages, but the page with a page template of "item" has the comment on it, and the pages with page templates of "item-comment" has the comment and forms twice.
![2016-09-11_grav_dual_comments](https://cloud.githubusercontent.com/assets/7863135/17605209/29e1890a-5fce-11e6-8c04-7747a0ce6964.png)

**Comment by flaviocopes** [comment]
I just tested a fresh "Blog site" skeleton now, right with caching enabled it's not working as expected. Need to fix this. The double form might be a theme thing.

**Comment by flaviocopes** [comment]
Fixed in the commit linked, issuing a release now

**Comment by mabushey** [comment]
Thanks! That fixed the comment caching issue.

It turns out that the Antimatter theme added comment support in commit 1735126. It was working right  (One set of comment blocks) until I upgraded the theme. The docs for the comment plugin should probably be updated, right now they tell you to add the comments it to `item.html.twig`, however `item.html.twig` already calls `partials/blog_item.html.twig` which includes the comments on line 75.

**Comment by flaviocopes** [comment]
Yep some themes already include the comments by default, but not everyone of them.
