### ISSUE TITLE
Comment is not saved. onFormProcessed is not called.

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav-plugin-comments#35]
This is the first time I try Comments plugin. The form is shown but comment is not saved.
I have tried on both localhost and a live site (email is working) but the problem still exists.
I have uploaded the site at https://github.com/tranduyhung/grav-skeleton-blog-site, I really appreciate if you can take a look and let me know what I am doing wrong.

I have also tried to modify the form from

```
form:
    name: comments
    fields:
```

to

```
forms:
   comments:
      fields:
```

but still the same.

As I have debugged, onFormProcessed function is never called.

Thank you!

**Comment by flaviocopes** [comment]
Which other plugins you have installed?

**Comment by tranduyhung** [comment]
Currently I am testing with Blog skeleton, you can see the list of plugins here https://github.com/tranduyhung/grav-skeleton-blog-site/tree/master/user/plugins.
It is the default Blog skeleton + Comments plugin installed,

**Comment by flaviocopes** [comment]
Mmm, looks like an issue in the latest Form release and Comments. @rhukster do you foresee any issue it might have with Comments adding a form to the page header dynamically? Maybe it's just events ordering?

**Comment by rhukster** [comment]
Actually yes, the forms are now processed and cached prior to page content being available in `onPageProcessed`. This way the forms are all available no matter which page you are on. This is how including forms from other pages is possible.  I didn't realize that comments plugin was adding a form dynamically.

This will require some additions in the form plugin to be able to support.. alternatively, comments might be able to be modified to modify/store the page in `onPageProcessed` like the forms plugin is doing.

**Comment by flaviocopes** [comment]
Should be fixed by the upcoming Form + Comments plugin release. Update when Grav notifies you of the update.
