### ISSUE TITLE
Problem with comments of more than 7 days

### ISSUE THREAD

**Issue by edwigemorin** [getgrav/grav-plugin-comments#37]
Hello, 

When I have comments with a date more than 7 days ago the comments page in the admin plugin (at admin/comments) is broken.

I would like to precise that I'm trying to migrate an old site into grav that's why I'm entering the comments with an old date.
Could you help ?
Thanks

**Comment by flaviocopes** [comment]
Fixed and released an update of the plugin, thanks for reporting!
