### ISSUE TITLE
'continue_link: false' frontmatter disables comment form

### ISSUE THREAD

**Issue by 4ndyy** [getgrav/grav-plugin-comments#39]
Hi,  

I'm using `continue_link: false` in frontmatter for some of my blog posts (because the continue_link is always visible regardless of summary settings). This frontmatter disables the comment form.  

I've worked around the issue by tweaking my blog_item.html.twig to include the comment partial after the `{% if not truncate %}` line.  

I admit I haven't researched the issue much, because it's very late and I just noticed it, but I can provide more info/QA as needed.

**Comment by flaviocopes** [comment]
It is probably a theme issue, with the Comments plugin Twig being placed in a wrong conditional.

**Comment by 4ndyy** [comment]
Hi. Thank you for your reply. Yes it is a theme issue. I am running a custom theme inherited from Antimatter from the Grav Blog Site skeleton.

I downloaded fresh copies of all the 1st party Team Grav skeletons to test, but the Blog Site is the only one that seems to natively support the Comments plugin - meaning, no comment form appears on blog pages when running the twentyfifteen skeleton for example.

I can continue testing a bit later, but since this isn't really an issue with the Comments plugin you can resolve this ticket if you like.
