### ISSUE TITLE
comments plugin is interpreting the enable_on_routes variable differently now.

### ISSUE THREAD

**Issue by ohnonot** [getgrav/grav-plugin-comments#40]
after the last grav update, comments have disappeared!
it seems the comments plugin is interpreting the enable_on_routes variable differently now.
i always had it as
```
enable_on_routes:
  - '/blog'
```
(this is still the default currently)

changing it to
```
enable_on_routes:
  - '/'
```
makes the comments re-appear.

my interpretation:
in my system.yaml, i'm telling grav to hide the ‘/blog’ route in urls.
it would seem that after the grav update, this is also internally applied to the twig environment?
am i correct?

also [see here](https://getgrav.org/forum#!/general:lost-functionality-after-up/ok-i-got-it-it-seems-the)

**Comment by flaviocopes** [comment]
I went back to Grav 1.0.9 but the behavior is always the same: if you're using /blog as your home alias, and you set `home.hide_in_urls`, using `/blog` in the enabled routes for Comments is not working, you need `/`. 

Do you remember from which version did you update?

**Comment by ohnonot** [comment]
it can't have been more than a few weeks, so from the previous release i guess.

unfortunately i just deleted some backups so i cannot say for sure, maybe i was wrong.

however, the route /blog still exists, it is only hidden from visitors, so i find the plugin's behavior illogical, esp. since the default config still uses `enable_on_routes: - /blog`.
i think this would deserve a mention in the README at the very least.

**Comment by hostragon-hosting** [comment]
... if someone is using a subdomain for Grav, please what should this: `enable_on_routes:` be ?

**Comment by flaviocopes** [comment]
@hostragon-hosting regarless of using Grav on a subdomain, or on its own domain, if you want comments to appear on `/blog` and child pages, you should add `/blog` to that list. If your home page points to `/blog`, add `/blog` even if you have `home.hide_in_urls` enabled, and the home page does not contain `/blog/` in the URL. You still need to include the Twig as described in https://github.com/getgrav/grav-plugin-comments/blob/develop/README.md#usage
