### ISSUE TITLE
Comments not working with Hydrogen theme (v5.4.1)

### ISSUE THREAD

**Issue by vitalitas** [getgrav/grav-plugin-comments#41]
Hi.

I'm new and do not have any Grav experience. As theme I'm using Hydrogen v5.4.1. Unfortunately comments (v1.2.5) aren't working with this theme. When I switch to Antimatter, then comments are usable.

When I submit a comment, it will show an error message like:
Ups, es gibt da ein Problem. Eingabewerte bitte noch mal prüfen und das Formular erneut absenden.

German for: Houston, we have a problem.

Furthermore there is a strange line below the submit button:
\<input type="hidden" id="form-nonce" name="form-nonce" value="c9563c67d98411fd8bdda80f5d4fac29" /\>

Is this fixable?

kind regards,
vitalitas

**Comment by flaviocopes** [comment]
Can you tell me step by step what you did to enable comments in Hydrogen, to replicate the exact scenario? Thanks

**Comment by vitalitas** [comment]
Yeeeehhaaa. I've installed Grav with link https://learn.getgrav.org/basics/installation.

Then I updated Grav an installed comments plugin by admin panel: admin panel --> plugins --> add --> comments plugin.

Now the version of Grav is v1.1.11 - Admin v1.2.7 and comments v1.2.5

The issue still exists.

**Comment by flaviocopes** [comment]
Where did you put the `{% include 'partials/comments.html.twig' %}` Twig?

**Comment by vitalitas** [comment]
I put it in <webspace-dir>/user/plugins/gantry5/engines/nucleus/templates/blog_item.html.twig.

The "add comment" is shown, without to add the twig-line. And even if I add it in the file above, the comment function isn't working. I shows now "Oops there was a problem, please check your input and submit the form again." The email address is valid in the email plugin. Also I can send emails from the command line in a ssh session.

The directory <webspace-dir>/user/data/comments/ was created after a comment was submitted, but there is not any file in.

**Comment by phideas** [comment]
Same problem with Helium theme. It seems to be the nonce output has escaped html chars. When I looked into html page source, there is:
` &lt;input type=&quot;hidden&quot; id=&quot;form-nonce&quot; name=&quot;form-nonce&quot; value=&quot;c14e68f72fb0504e88e855ef228fa48b&quot; /&gt;`
Any idea how to solve this bug, or where could be the core of this problem?

**Comment by phideas** [comment]
This quick hack solves the problem for now. Ruling out the escaping (add raw) for nonce input field in user/plugins/comments/templates/partials/comments.html.twig
`{{ nonce_field('form', 'form-nonce')|raw) }}`

**Comment by flaviocopes** [comment]
@phideas That's the correct solution of the problem - going to commit it and push a release
