### ISSUE TITLE
Feature request: turn off email notifications.

### ISSUE THREAD

**Issue by taivu** [getgrav/grav-plugin-comments#42]
With every comment, an email gets sent. Can we have options to turn off emailing for specific routes, similar to `enable_on_routes:` and `disable_on_routes:`?

suggesting `email_on_routes` or `no_email_on_routes`

**Comment by flaviocopes** [comment]
The comments form is defined in https://github.com/getgrav/grav-plugin-comments/blob/develop/comments.yaml. You can override it in `user/config/plugins/comments.yaml, and remove the line 

```
        - email:
            subject: PLUGIN_COMMENTS.EMAIL_NEW_COMMENT_SUBJECT
            body: "{% include 'forms/data.html.twig' %}"
```
