### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-plugin-comments#44]
Hello,

I created this issue in order to know what's next for this plugin?  
It's a great plugin but we could add several features to make it even better:

* Edit/delete comments from the admin plugin
* See the comment in the admin plugins
* Be able to answer to a comment with a notification system to let the comment's author know someone just posted an answer on his comment

In fact, something like the Wordress comment system + [this plugin](https://wordpress.org/plugins/subscribe-to-comments-reloaded/).

Thanks and keep up the good work!

**Comment by flaviocopes** [comment]
All good suggestions. The plugin can surely be improved, if you want to start working on any of those features, we'll gladly merge PRs.
