### ISSUE TITLE
Comment plugin sends email on recapture failure

### ISSUE THREAD

**Issue by rsmarples** [getgrav/grav-plugin-comments#45]
I get zero comments on a page, but plenty of attempts in my mail.

**Comment by rhukster** [comment]
Just make sure you put the email 'process' after the 'captcha' process in your form definition.

**Comment by rsmarples** [comment]
I assume in `config/plugins/comments.yaml` in the lower process section?
I don't know how to test it as I'm not a robot, but I guess I can close this if no spammage hits after a few days.

**Comment by flaviocopes** [comment]
Moved the default captcha check before the email is sent

**Comment by flaviocopes** [comment]
Just do the same as https://github.com/getgrav/grav-plugin-comments/commit/fac87e9bb5b9a32d9e9d099197bcde9860984ba1 in your config/plugins/comments.yaml

**Comment by rsmarples** [comment]
I did this, but now get 503 Service unavailable errors when posting comments.
Remove recapture from the process allows comments to be made.
The only message in the logs is that the PHP_FPM service timed out.
