### ISSUE TITLE
Latest comments widget

### ISSUE THREAD

**Issue by Salvatos** [getgrav/grav-plugin-comments#49]
I would like a latest comments widget that could be placed in the sidebar to pull from all articles/pages. I went and hacked something together based on the admin panel display, but it could use someone more knowledgeable bringing it in line with Grav's standards and generally making it less hacky.

Also, one missing feature is that I would like to link to each comment's post/page, and I don't know how to safely derive the URLs from the filePath.

I added this bit to function initializeFrontend() in comments.php (~line 130):
```
EDIT: SEE UPDATED CODE BELOW
```

I created a new function based on getLastComments(); essentially the same with irrelevant parts removed and a limit to the array size:
```
EDIT: SEE UPDATED CODE BELOW
```

Example output (you could also show the date):
```
EDIT: SEE UPDATED CODE BELOW
```

I hope posting it like this isn't too inconvenient. Any help would be appreciated!

**Comment by Salvatos** [comment]
I changed this a bit today to make it a little more configurable by putting the `limit` on the theme side rather than logic side. Changes to `comments.php` are now as follows for `initializeFrontend()`:
```
        // Load Last Comments widget
        $this->grav['twig']->lastcomments = $this->getLastCommentsFeed();
```
And the function itself:
```
    /**
     * Return the last comments public feed
     */
    private function getLastCommentsFeed() {
        $files = [];
        $files = $this->getFilesOrderedByModifiedDate();
        $comments = [];

        foreach($files as $file) {
            $data = Yaml::parse(file_get_contents($file->filePath));

            for ($i = 0; $i < count($data['comments']); $i++) {
                $commentTimestamp = \DateTime::createFromFormat('D, d M Y H:i:s', $data['comments'][$i]['date'])->getTimestamp();

                $data['comments'][$i]['pageTitle'] = $data['title'];
                $data['comments'][$i]['filePath'] = $file->filePath;
                $data['comments'][$i]['timestamp'] = $commentTimestamp;
            }
            if (count($data['comments'])) {
                $comments = array_merge($comments, $data['comments']);
            }
        }

        // Order comments by date
        usort($comments, function($a, $b) {
            return !($a['timestamp'] > $b['timestamp']);
        });

        return (object)array(
            "comments" => $comments
        );
    }
```
With a "comfeedlimit" in the output so that parameter won't need to be reset every time the plugin is updated:
```
<div class="sidebar-content">
	<h5>Latest comments</h5>
	<ul>
		{% set comfeedlimit = 4 %}
		{% for comment in grav.twig.lastcomments.comments %}
			{% if loop.index <= comfeedlimit %}
		<li><span class="comment-feed-author">{{comment.author}}</span> on <a href="{{base_url_relative ~ comment.route}}#comments" class="comment-feed-page">{{comment.pageTitle}}</a>:<br />
		<span class="comment-feed-comment">{{comment.text|truncate(35)}}</span></li>
			{% endif %}
		{% endfor %}
	</ul>
</div>
```

**Comment by 5Hu** [comment]
Thank you for this. Works very good.
Is it possible to make `{{comment.pageTitle}}` a clickable link to the article where the comment was written?

**Comment by Salvatos** [comment]
I do in fact have it set up as a link on my site, with a change to `onFormProcessed()`. Since this changes the way comments are written to files, you may encounter errors if you have existing comments on your site. You would then need to add the route to those existing comments manually, unfortunately, so make sure to try this in a development environment first. Also I'm not sure I'm using the best way to generate the URL, so there may be breakage in some scenarios.

In `comments.php`, near the original lines 222 **and** 232, add a "route" parameter to `onFormProcessed()` like so:
```
                        'author' => $name,
                        'route' => $path,
```
And for display:
```
<a href="{{base_url_relative ~ comment.route}}#comments">{{comment.pageTitle}}</a>
```
You may have to add an element with `id="comments"` somewhere if you want to scroll the page down to that section; my theme didn't have one by default so I added one near the start of `comments.html.twig`. Or remove `#comments` from the URL to just link to the page.

Hope that helps! :)

**Comment by 5Hu** [comment]
For auto scroll down to the comments I changed line 48 in `user/plugins/comments/templates/partials/comments.html.twig` from ` <table>` to ` <table id="comments">`. With this change I don't have to edit someting on the theme.

Thank you for this very good extension and your help. 
It would be nice if this finds the way directly into the plugin.

**Comment by Salvatos** [comment]
Glad I could help :) However, note that by placing it there the link won't work if there are no comments on a page. That's not a problem if you only link to it from the latest comments feed (since no comments means no link), but if you were to add a link to comments next to the article titles for example, it wouldn't work in those cases. That's why I placed mine at the top, just after `{% if grav.twig.enable_comments_plugin %}`.

I also make my template changes in `user/themes/my-theme/templates/partials/comments.html.twig` so they don't get rewritten on updates (keeping the changes in `comments.php` will be enough trouble as it is!).
