### ISSUE TITLE
routes strings or not?

### ISSUE THREAD

**Issue by jeremycherfas** [getgrav/grav-plugin-comments#50]
In the `comments.yaml` section on routes, some of the values seem to be set as strings, others not.

````
enable_on_routes:
  - '/blog'

disable_on_routes:
  - /blog/blog-post-to-ignore
  - /ignore-this-route
  #- '/blog/daring-fireball-link'
````

Does it make any difference?

**Comment by flaviocopes** [comment]
It's not always necessary to have quotes, they are optional but required in some cases, see https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml for more info
