### ISSUE TITLE
Comments remain when their parent page is removed

### ISSUE THREAD

**Issue by Salvatos** [getgrav/grav-plugin-comments#51]
When a page is deleted (from the admin panel or otherwise), its associated comments file remains in place. For most people that's probably not a problem visible in the front-end, but it creates some clutter. Not a big deal considering the likely size of the files involved. For me it's a bit more of a problem because I show the most recent comments in a sidebar, so they'll keep showing up even if their article is deleted or made invisible.

Would it be useful to have something in the plugin's admin page that checks for orphaned comments and offers to purge them? It could also offer to reroute comments for pages that have been moved or renamed.

**Comment by flaviocopes** [comment]
Good suggestion, the plugin can listen for `onAdminAfterDelete` and clean up the page. 
A similar thing should apply if the page is moved, but in this case there is no event to listen to, it's a bit trickier.
