### ISSUE TITLE
Problem processing posts

### ISSUE THREAD

**Issue by RamblingRoss** [getgrav/grav-plugin-comments#52]
Hi

After a recent update I'm finding the comments plug-in is no longer working.

To remove misconfiguration issues within my theme I have downloaded the "Helium Site" theme (https://github.com/gantry/gantry5), added in the grav-plugin-comments plugin and updated its configuration file to be enabled on the '/pages/blog' route.

The plugin appears correctly, but when POSTing a comment to the blog post nothing appears to happen.

By adding a liberal smattering of trace statements through the code it appears the function onFormProcessed within grav-plugins-conmments is never getting called. The same appears to be true for the form plugin as well.

I have obviously got some major misconfigraton going on... but can't figure out what, especially as the only change I made to the "Helium Site" theme was to download the grav-plugin-comments plugin and update its comments.yaml to enable on the appropriate route.

Any ideas what I may be doing wrong?

**Comment by RamblingRoss** [comment]
After a bit of further investigation, I believe commit ddf6e40 may be the route cause.

It has added a requirement for forms to have a 'data' field present in the POST data, not something that is being set by the off the shelf template.

**Comment by 5Hu** [comment]
Same here. Downloaded the actual grav-admin-v1.2.4.zip and getgrav-grav-plugin-comments-1.2.6-0-gc71e356.zip.
The comments plugin is showing but nothing appears to happen if I click on submit.
Also there is nothing written in `user/data/comments/`.

**Comment by Neiromaster** [comment]
I checked.
1. If the Email settings are not correct, the comment is not saved.
2. If the user is logged in, then an error occurs:
  Validation failed:
  Missing required field: Name
  Missing required field: Email

**Comment by flaviocopes** [comment]
Fixed in the latest release

**Comment by flaviocopes** [comment]
The new release should appear in ~1 hour in the GPM, comment back if you still have issues

**Comment by Neiromaster** [comment]
Ok! So far, so good!
