### ISSUE TITLE
Email subject

### ISSUE THREAD

**Issue by Neiromaster** [getgrav/grav-plugin-comments#54]
The subject line does not display wildcard text, but "PLUGIN_COMMENTS.EMAIL_NEW_COMMENT_SUBJECT"

**Comment by 5Hu** [comment]
It looks like the language conversion is not working. As a workaround you can change in `user/config/plugins/comments.yaml` the `subject` parameter in the  `process` block from
```
subject: PLUGIN_COMMENTS.EMAIL_NEW_COMMENT_SUBJECT
```
to
```
subject: "[New Comment] from {{ form.value.name|e }}"
```

Note: This is for english language only. If you need other translation look into `user/plugins/comments/languages.yaml`. You can find the right conversion in your language block right behind the placeholder `EMAIL_NEW_COMMENT_SUBJECT:`.

**Comment by Neiromaster** [comment]
What will be substituted instead of New Comment?

**Comment by 5Hu** [comment]
There is no substitution. The email subject is `PLUGIN_COMMENTS.EMAIL_NEW_COMMENT_SUBJECT`.
