### ISSUE TITLE
Undefined Index: lang (etc)

### ISSUE THREAD

**Issue by sirdeggen** [getgrav/grav-plugin-comments#55]
Found a bug. Fixed it.

I don't really know how to use github... so I'll write here and then try to suggest the edit.
Within comments.php line 192

the post variable grabbing lines should be updated from:

                $lang = filter_var(urldecode($post['lang']), FILTER_SANITIZE_STRING);
                $path = filter_var(urldecode($post['path']), FILTER_SANITIZE_STRING);
                $text = filter_var(urldecode($post['text']), FILTER_SANITIZE_STRING);
                $name = filter_var(urldecode($post['name']), FILTER_SANITIZE_STRING);
                $email = filter_var(urldecode($post['email']), FILTER_SANITIZE_STRING);
                $title = filter_var(urldecode($post['title']), FILTER_SANITIZE_STRING);

to

                $lang = filter_var(urldecode($_POST['lang']), FILTER_SANITIZE_STRING);
                $path = filter_var(urldecode($_POST['path']), FILTER_SANITIZE_STRING);
                $text = filter_var(urldecode($_POST['text']), FILTER_SANITIZE_STRING);
                $name = filter_var(urldecode($_POST['name']), FILTER_SANITIZE_STRING);
                $email = filter_var(urldecode($_POST['email']), FILTER_SANITIZE_STRING);
                $title = filter_var(urldecode($_POST['title']), FILTER_SANITIZE_STRING);

This was breaking the functionality of almost the whole plugin.

**Comment by flaviocopes** [comment]
Do you have a theme that overrides `templates/partials/comments.html.twig`, but misses this line https://github.com/getgrav/grav-plugin-comments/blob/develop/templates/partials/comments.html.twig#L2?

Is this the case?

**Comment by flaviocopes** [comment]
(I assume you are running a recent Form plugin release)

**Comment by Salvatos** [comment]
Thanks @flaviocopes that was the issue for me after updating a bunch of plugins.
