### ISSUE TITLE
Languages - Brazilian Portuguese - pt-BR

### ISSUE THREAD

**Issue by afsoeiro** [getgrav/grav-plugin-comments#71]
Hi,
I had problems with the comments not being translated into Brazilian Portuguese. I found out that the code in the languages.yaml file is 'pt-br'. The usual language code for Brasilian Portuguese in all system is pt-BR. So, correcting that language code in the file gets translation working for this plugin too. I did in my website, and suggest it gets done in there too. I did not do it now because I have no access.

**Comment by rhukster** [comment]
Anyone can create a PR. just fork, edit, and submit PR.
