### ISSUE TITLE
captcha verification not working

### ISSUE THREAD

**Issue by mi1anshrestha** [getgrav/grav-plugin-comments#8]
user can post comments (comment email sent) without a need of verification (Google)!

**Comment by flaviocopes** [comment]
I'm not seeing this bug. With the default comments.yaml configuration, the captcha is a required field and so is validated before processing the form.

Can you paste your comments.yaml (strip the recaptcha secret/site keys) and provide an explanation of what happens?

**Comment by mi1anshrestha** [comment]
Please check !
===
![re-captcha-comment](https://cloud.githubusercontent.com/assets/15952978/11318405/ec99521e-9078-11e5-9498-e6e47133555e.JPG)
comment.yaml config 
===
enabled: true
enable_on_routes:
  - /blog
disable_on_routes:
  - /blog/blog-post-to-ignore
  - /ignore-this-route
form:
  name: comments
  fields:
    -
      name: name
      label: Name
      placeholder: 'Enter your name'
      autofocus: 'on'
      autocomplete: 'on'
      type: text
      validate:
        required: true
    -
      name: email
      label: Email
      placeholder: 'Enter your email address'
      type: email
      validate:
        required: true
    -
      name: text
      label: Message
      placeholder: 'Enter your message'
      type: textarea
      validate:
        required: true
    -
      name: date
      type: hidden
      process:
        fillWithCurrentDateTime: true
    -
      name: title
      type: hidden
      evaluateDefault: grav.page.header.title
    -
      name: lang
      type: hidden
      evaluateDefault: grav.language.getLanguage
    -
      name: path
      type: hidden
      evaluateDefault: grav.uri.path
    -
      name: g-recaptcha-response
      label: Captcha
      type: captcha
      recatpcha_site_key: **********************************
      recaptcha_not_validated: 'Captcha not valid!'
      validate:
        required: true
      process:
        ignore: true
  buttons:
    -
      type: submit
      value: Submit
  process:
    -
      email:
        subject: '[New Comment] from {{ form.value.name|e }}'
        body: '{% include ''forms/data.html.twig'' %}'
    -
      captcha:
        recatpcha_secret: ********************************
    -
      addComment: null
    -
      message: 'Thank you for writing your comment!'

**Comment by flaviocopes** [comment]
Cannot recreate this too. Are you using the latest version of Grav, the Form and Comments Plugins? 
If yes, zip your user/ folder and send it to me via Gitter PM, so I can try directly your setup.

**Comment by abooks23** [comment]
yes  all latest ver.
