### ISSUE TITLE
Comment stored outside of "user/data/comments"  folder

### ISSUE THREAD

**Issue by sixo** [getgrav/grav-plugin-comments#80]
Since some time I'm getting spam comments which are not stored inside of the usual `user/data/comments`. Instead there's a file created directly in `user/data/` folder. 
In comparison to the normal valid comments, this yaml file name is mangled (it seems to contain unicode char codes, like `&#x20;`).

1. Is this file rendered somewhere? I was assuming that if it is outside of the comments folder and there's no mapping to page route, then it won't be rendered. 

2. How could I enable automatic IP logging for everyone who posts a comment? 

3. How to enable IP address blocking in grav.

**Comment by rhukster** [comment]
I think this partly related to #86.  I have a fix for this, and will release shortly.

**Comment by rhukster** [comment]
Fixed
