### ISSUE TITLE
Grav 1.6.19 on PHP 7.4.1 is broken (again?)

### ISSUE THREAD

**Issue by spectroman** [getgrav/grav-plugin-comments#81]
I have tried Grav on 7.4 before and I realized it was broken in several places. I fixed a couple of those but more kept appearing in different places, I decided to wait for an official update.

According to https://github.com/getgrav/grav/issues/2750 this updated supposedly have fixed some of the problems I have seen before. But as I am testing it now, I get again:

```Server Error
Sorry, something went terribly wrong!

E_NOTICE - Trying to access array offset on value of type null
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

And at the log, there is a non polite message:

`Trying to access array offset on value of type null - Trace: #0 /data/webserver/www-gravtest-com/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError() getgrav/grav#1 /data/webserver/www-gravtest-com/user/plugins/comments/comments.php(350): Grav\Common\Debugger->deprecatedErrorHandler() getgrav/grav#2 /data/webserver/www-gravtest-com/user/plugins/comments/comments.php(77): Grav\Plugin\CommentsPlugin->fetchComments() getgrav/grav#3 /data/webserver/www-gravtest-com/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\CommentsPlugin->onTwigSiteVariables() getgrav/grav#4 /data/webserver/www-gravtest-com/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() getgrav/grav#5 /data/webserver/www-gravtest-com/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() getgrav/grav#6 /data/webserver/www-gravtest-com/system/src/Grav/Common/Grav.php(377): RocketTheme\Toolbox\Event\EventDispatcher->dispatch() getgrav/grav#7 /data/webserver/www-gravtest-com/system/src/Grav/Common/Twig/Twig.php(363): Grav\Common\Grav->fireEvent() getgrav/grav#8 /data/webserver/www-gravtest-com/system/src/Grav/Common/Service/OutputServiceProvider.php(28): Grav\Common\Twig\Twig->processSite() getgrav/grav#9 /data/webserver/www-gravtest-com/vendor/pimple/pimple/src/Pimple/Container.php(118): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}() getgrav/grav#10 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/RenderProcessor.php(28): Pimple\Container->offsetGet() getgrav/grav#11 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RenderProcessor->process() getgrav/grav#12 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#13 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#14 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerAssetsProcessor->process() getgrav/grav#15 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#16 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/PagesProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#17 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process() getgrav/grav#18 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#19 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#20 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process() getgrav/grav#21 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#22 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#23 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process() getgrav/grav#24 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#25 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#26 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process() getgrav/grav#27 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#28 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#29 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process() getgrav/grav#30 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#31 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#32 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process() getgrav/grav#33 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#34 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#35 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process() getgrav/grav#36 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#37 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#38 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process() getgrav/grav#39 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#40 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#41 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process() getgrav/grav#42 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#43 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#44 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process() getgrav/grav#45 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#46 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#47 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process() getgrav/grav#48 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#49 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#50 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process() getgrav/grav#51 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#52 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#53 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process() getgrav/grav#54 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#55 /data/webserver/www-gravtest-com/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#56 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process() getgrav/grav#57 /data/webserver/www-gravtest-com/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#58 /data/webserver/www-gravtest-com/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle() getgrav/grav#59 /data/webserver/www-gravtest-com/index.php(53): Grav\Common\Grav->process() getgrav/grav#60 {main}
`

I kinda feels like, more of the same?

More details:

```php --version
PHP 7.4.1 (cli) (built: Dec 18 2019 12:59:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

And:

```httpd -V
Server version: Apache/2.4.41 (Unix)
Server built:   Aug 13 2019 22:44:41
Server's Module Magic Number: 20120211:88
Server loaded:  APR 1.7.0, APR-UTIL 1.6.1
Compiled using: APR 1.7.0, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_PROC_PTHREAD_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```

Running on Arch Linux.

Theme test Receptar.

**Comment by spectroman** [comment]
Yeah, just to confirm this... , if I disable the Comments plugin the pages does work!

but you probably already knew that :)

Like that I have hopes to develop a new website with the comments disabled until there is an update to fix this.

**Comment by NicoHood** [comment]
I have the same issue.

**Comment by rhukster** [comment]
Fixed
