### ISSUE TITLE
Default design - Difficult to read

### ISSUE THREAD

**Issue by karibuTW** [getgrav/grav-plugin-comments#85]
Hello guys, the default design makes it very difficult to read the comments.

I am not good in modifying the theme or else. Any idea how to make it better to read?

See how it looks like:
https://freedif.org/community-forum-software-how-to-install-vanilla-message-board

(Full of spam tho)

**Comment by rhukster** [comment]
There is very little default styling in this plugin.  You are expected to add your own to fit into your own design/theme.
