### ISSUE TITLE
please consider making a new plugin release

### ISSUE THREAD

**Issue by GeoffWilliams** [getgrav/grav-plugin-comments#9]
Version 1.0.1 as installed with `./bin/gpm` is missing the nonce field in the template file:
```
 {{ nonce_field('form', 'form-nonce') }}
```

Which causes all submitted comments to receive the response "ops there was a problem, please check your input and submit the form again."

## Workaround
The fixed template is already in the repository, its just not in a release.  Users can fix the system by updating the local copy of the template at `user/plugins/comments/templates/partials/comments.html.twig` with the one from 
https://github.com/getgrav/grav-plugin-comments/blob/develop/templates/partials/comments.html.twig or add the above nonce field just before the closing `</form>` tag

**Comment by superlou** [comment]
Even though 1.1.0 isn't marked as the latest release on Github, it looks like that's what installed from the admin menu in my installation.  This includes the `{{ none_field ... }}`.

**Comment by flaviocopes** [comment]
Not sure how I missed this issue! Yes, a new release of Comments is now available with nonces support. Our release script does not make Github mark a tagged release as the latest, not sure why! But today 1.1.1 was out too.
